### ISSUE TITLE
MonoCross.Droid refernce issue in "MonoCross Android Container" VS2010 template

### ISSUE THREAD

**Issue by SamusArin** [MonoCross/MonoCross#1]
Oh man, I think the problem was that in my MonoCrossFragments.Droid project I left the MonoCross.Navigation.dll file in the MonoCross subdirectory along with the MonoCross.Navigation.MD.dll.  It was left over from how I created the MonoCrossFragments.Droid project from the base MonoCrossFragments project.  Ugh.  Well, I know there is still a problem with the MonoCross project template references, because I ran into this issue a while back, and as of now I'm using all the MonoCross assemblies right from where I unzipped the 1.0.2 source, and not the ones included with the templates.

---

Hello.

Before I begin, here are some specs:

Windows 7 Enterprise x64
Visual Studio 2010 Ult SP1
Android-SDK (1.6-4.1)
Mono for Android 4.2.6
MonoCross 1.0.2
MonoCross Utilities 1.0.2
MonoCross Templates

I just got done manually creating a multi-platform solution/project in visual studio from scratch following the layout from the CustomerManagement example:

```
 MonoCrossFragments.Droid (VS2010 Solution)

      Container (folder)
           MonoCrossFragments.Droid (MX Android Container Project)

      Data (folder)
           MonoCrossFragments.Data.MD (Mono/Android Class Lib Project)

      MonoCrossFragments.MD (MX Android App Project)

      MonoCrossFragments.Shared.MD (Mono/Android Class Lib Project)
```

After compiling the near empty solution, I got the error message:

"Error  1   The type 'Android.App.ListActivity' is defined in an assembly that is not referenced. You must add a reference to assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.   C:\My Projects\TestArea\MonoCross\MonoCrossFragmentsRoot\MonoCrossFragments\MonoCrossFragments.Droid\Views\MessageView.cs   16  18  MonoCrossFragments.Droid"

The MonoCross Android Container project this was happening in, MonoCrossFragments.Droid, did in fact have a reference to the Mono.Android assembly residing in my "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v2.2\" directory, which was automatically added by the template.

So, I tried to clean the solution and rebuild, then tried removing and adding back the Mono.Android reference, and then tried selecting a newer version of the Android platform (4.0) (and yes, I reopend my solution after changing).  None of which worked.

Assuming that the MonoCross.Droid.dll assembly may be a fault for not properly referencing Mono.Android.dll, I copied a MonoCross.Droid.dll file from another, working project.  This fixed the Mono.Droid reference error, but then gave:

Error   1   Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Android.Dialog, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Android.Dialog.dll'
   at Monodroid.Tuner.MonoDroidResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(List`1 assemblies, AssemblyDefinition assembly)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(List`1 assemblies, AssemblyDefinition assembly)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute() MonoCrossFragments.Droid

and so I copied a Android.Dialog.dll assembly into the directory where MonoCross.Droid.dll resided (which was the directory named "MonoCross" in the root of my project folder, or MonoCrossFragments.Droid\MonoCross).  Then it compiled.

So, it seems like there is something going on with the reference to Mono.Android from within the MonoCross.Droid assembly that is included with the MonoCross Android Container project template.

Has anyone else reported issues with this Mono.Droid reference ?

Thanks, Dan.

**Comment by sam-lippert** [comment]
New templates should be created for VS2019
